#!/usr/bin/env bash
#
# Configure dotfiles with symlinks and run brew(if osx)

# Exit on errors
set -e

# Change dir to dotfiles dir
cd "$(dirname "$0")"/..

DOTFILESDIR=$(pwd -P)
echo "dotfile dir: $DOTFILESDIR"

link_file() {
  # $1 - source file or dir to link
  # $2 - destination file or dir
  if [ -e "$2" ]; then
      rm -rf "$2"
      echo "Existing $2 removed!"
  fi
  ln -s "$1" "$2" && echo "Linked $1 to $2"
}

symlink_files() {
  for src in $(find -H $DOTFILESDIR -maxdepth 4 -name '*.symlink' -not -path '*.git*')
  do
      # remove the extension '.symlink'
      dst="$HOME/.$(basename "${src%.*}")"
      link_file "$src" "$dst"
  done
}

install_files() {
  for src in $(find -H $DOTFILESDIR -maxdepth 4 -name 'install.sh' -not -path '*.git*')
  do
      echo "Installing $(dirname $src)"
      source "$src"
  done
}

symlink_files
install_files

set +e
